FROM resin/%%RESIN_MACHINE_NAME%%-python

ENV INITSYSTEM on

ENV DEVICE %%RESIN_MACHINE_NAME%%

RUN apt-get -q update && apt-get install -yq --no-install-recommends \
	cowsay \
	&& rm -rf /var/lib/apt/lists/*

RUN /usr/games/cowsay "Install dependencies in this script. This happens on the build servers!"

ADD ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["python", "hello.py"]
